/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as CleanerRouteImport } from './routes/cleaner'
import { Route as CaretakerRouteImport } from './routes/caretaker'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as CleanerIndexRouteImport } from './routes/cleaner.index'
import { Route as CaretakerIndexRouteImport } from './routes/caretaker.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffUserIdRouteImport } from './routes/staff.$userId'
import { Route as ReportNewRouteImport } from './routes/report.new'
import { Route as CleanerTasksRouteImport } from './routes/cleaner.tasks'
import { Route as CleanerSyncRouteImport } from './routes/cleaner.sync'
import { Route as CaretakerTasksRouteImport } from './routes/caretaker.tasks'
import { Route as CaretakerSyncRouteImport } from './routes/caretaker.sync'
import { Route as CaretakerNewRouteImport } from './routes/caretaker.new'
import { Route as CaretakerChecklistRouteImport } from './routes/caretaker.checklist'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBlocksRouteImport } from './routes/admin.blocks'
import { Route as StaffUserIdIndexRouteImport } from './routes/staff.$userId.index'
import { Route as StaffUserIdTasksRouteImport } from './routes/staff.$userId.tasks'
import { Route as StaffUserIdSyncRouteImport } from './routes/staff.$userId.sync'
import { Route as StaffUserIdNewRouteImport } from './routes/staff.$userId.new'
import { Route as CleanerTasksTaskIdRouteImport } from './routes/cleaner.tasks.$taskId'
import { Route as CaretakerTasksTaskIdRouteImport } from './routes/caretaker.tasks.$taskId'
import { Route as AdminTasksTaskIdRouteImport } from './routes/admin.tasks.$taskId'
import { Route as AdminStockScanRouteImport } from './routes/admin.stock.scan'
import { Route as AdminStockItemIdRouteImport } from './routes/admin.stock.$itemId'
import { Route as StaffUserIdTasksTaskIdRouteImport } from './routes/staff.$userId.tasks.$taskId'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerRoute = CleanerRouteImport.update({
  id: '/cleaner',
  path: '/cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerRoute = CaretakerRouteImport.update({
  id: '/caretaker',
  path: '/caretaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportRoute,
} as any)
const CleanerIndexRoute = CleanerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CleanerRoute,
} as any)
const CaretakerIndexRoute = CaretakerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaretakerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffUserIdRoute = StaffUserIdRouteImport.update({
  id: '/staff/$userId',
  path: '/staff/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportNewRoute = ReportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReportRoute,
} as any)
const CleanerTasksRoute = CleanerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CleanerRoute,
} as any)
const CleanerSyncRoute = CleanerSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => CleanerRoute,
} as any)
const CaretakerTasksRoute = CaretakerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CaretakerRoute,
} as any)
const CaretakerSyncRoute = CaretakerSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => CaretakerRoute,
} as any)
const CaretakerNewRoute = CaretakerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CaretakerRoute,
} as any)
const CaretakerChecklistRoute = CaretakerChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => CaretakerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlocksRoute = AdminBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AdminRoute,
} as any)
const StaffUserIdIndexRoute = StaffUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffUserIdRoute,
} as any)
const StaffUserIdTasksRoute = StaffUserIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => StaffUserIdRoute,
} as any)
const StaffUserIdSyncRoute = StaffUserIdSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => StaffUserIdRoute,
} as any)
const StaffUserIdNewRoute = StaffUserIdNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffUserIdRoute,
} as any)
const CleanerTasksTaskIdRoute = CleanerTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => CleanerTasksRoute,
} as any)
const CaretakerTasksTaskIdRoute = CaretakerTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => CaretakerTasksRoute,
} as any)
const AdminTasksTaskIdRoute = AdminTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AdminTasksRoute,
} as any)
const AdminStockScanRoute = AdminStockScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockItemIdRoute = AdminStockItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AdminStockRoute,
} as any)
const StaffUserIdTasksTaskIdRoute = StaffUserIdTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => StaffUserIdTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/caretaker': typeof CaretakerRouteWithChildren
  '/cleaner': typeof CleanerRouteWithChildren
  '/report': typeof ReportRouteWithChildren
  '/admin/blocks': typeof AdminBlocksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/sync': typeof AdminSyncRoute
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/caretaker/checklist': typeof CaretakerChecklistRoute
  '/caretaker/new': typeof CaretakerNewRoute
  '/caretaker/sync': typeof CaretakerSyncRoute
  '/caretaker/tasks': typeof CaretakerTasksRouteWithChildren
  '/cleaner/sync': typeof CleanerSyncRoute
  '/cleaner/tasks': typeof CleanerTasksRouteWithChildren
  '/report/new': typeof ReportNewRoute
  '/staff/$userId': typeof StaffUserIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/caretaker/': typeof CaretakerIndexRoute
  '/cleaner/': typeof CleanerIndexRoute
  '/report/': typeof ReportIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/stock/$itemId': typeof AdminStockItemIdRoute
  '/admin/stock/scan': typeof AdminStockScanRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/caretaker/tasks/$taskId': typeof CaretakerTasksTaskIdRoute
  '/cleaner/tasks/$taskId': typeof CleanerTasksTaskIdRoute
  '/staff/$userId/new': typeof StaffUserIdNewRoute
  '/staff/$userId/sync': typeof StaffUserIdSyncRoute
  '/staff/$userId/tasks': typeof StaffUserIdTasksRouteWithChildren
  '/staff/$userId/': typeof StaffUserIdIndexRoute
  '/staff/$userId/tasks/$taskId': typeof StaffUserIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/blocks': typeof AdminBlocksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/sync': typeof AdminSyncRoute
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/caretaker/checklist': typeof CaretakerChecklistRoute
  '/caretaker/new': typeof CaretakerNewRoute
  '/caretaker/sync': typeof CaretakerSyncRoute
  '/caretaker/tasks': typeof CaretakerTasksRouteWithChildren
  '/cleaner/sync': typeof CleanerSyncRoute
  '/cleaner/tasks': typeof CleanerTasksRouteWithChildren
  '/report/new': typeof ReportNewRoute
  '/admin': typeof AdminIndexRoute
  '/caretaker': typeof CaretakerIndexRoute
  '/cleaner': typeof CleanerIndexRoute
  '/report': typeof ReportIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/stock/$itemId': typeof AdminStockItemIdRoute
  '/admin/stock/scan': typeof AdminStockScanRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/caretaker/tasks/$taskId': typeof CaretakerTasksTaskIdRoute
  '/cleaner/tasks/$taskId': typeof CleanerTasksTaskIdRoute
  '/staff/$userId/new': typeof StaffUserIdNewRoute
  '/staff/$userId/sync': typeof StaffUserIdSyncRoute
  '/staff/$userId/tasks': typeof StaffUserIdTasksRouteWithChildren
  '/staff/$userId': typeof StaffUserIdIndexRoute
  '/staff/$userId/tasks/$taskId': typeof StaffUserIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/caretaker': typeof CaretakerRouteWithChildren
  '/cleaner': typeof CleanerRouteWithChildren
  '/report': typeof ReportRouteWithChildren
  '/admin/blocks': typeof AdminBlocksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/sync': typeof AdminSyncRoute
  '/admin/tasks': typeof AdminTasksRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/caretaker/checklist': typeof CaretakerChecklistRoute
  '/caretaker/new': typeof CaretakerNewRoute
  '/caretaker/sync': typeof CaretakerSyncRoute
  '/caretaker/tasks': typeof CaretakerTasksRouteWithChildren
  '/cleaner/sync': typeof CleanerSyncRoute
  '/cleaner/tasks': typeof CleanerTasksRouteWithChildren
  '/report/new': typeof ReportNewRoute
  '/staff/$userId': typeof StaffUserIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/caretaker/': typeof CaretakerIndexRoute
  '/cleaner/': typeof CleanerIndexRoute
  '/report/': typeof ReportIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/stock/$itemId': typeof AdminStockItemIdRoute
  '/admin/stock/scan': typeof AdminStockScanRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/caretaker/tasks/$taskId': typeof CaretakerTasksTaskIdRoute
  '/cleaner/tasks/$taskId': typeof CleanerTasksTaskIdRoute
  '/staff/$userId/new': typeof StaffUserIdNewRoute
  '/staff/$userId/sync': typeof StaffUserIdSyncRoute
  '/staff/$userId/tasks': typeof StaffUserIdTasksRouteWithChildren
  '/staff/$userId/': typeof StaffUserIdIndexRoute
  '/staff/$userId/tasks/$taskId': typeof StaffUserIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/caretaker'
    | '/cleaner'
    | '/report'
    | '/admin/blocks'
    | '/admin/login'
    | '/admin/new'
    | '/admin/stock'
    | '/admin/sync'
    | '/admin/tasks'
    | '/admin/users'
    | '/caretaker/checklist'
    | '/caretaker/new'
    | '/caretaker/sync'
    | '/caretaker/tasks'
    | '/cleaner/sync'
    | '/cleaner/tasks'
    | '/report/new'
    | '/staff/$userId'
    | '/admin/'
    | '/caretaker/'
    | '/cleaner/'
    | '/report/'
    | '/staff/'
    | '/admin/stock/$itemId'
    | '/admin/stock/scan'
    | '/admin/tasks/$taskId'
    | '/caretaker/tasks/$taskId'
    | '/cleaner/tasks/$taskId'
    | '/staff/$userId/new'
    | '/staff/$userId/sync'
    | '/staff/$userId/tasks'
    | '/staff/$userId/'
    | '/staff/$userId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/blocks'
    | '/admin/login'
    | '/admin/new'
    | '/admin/stock'
    | '/admin/sync'
    | '/admin/tasks'
    | '/admin/users'
    | '/caretaker/checklist'
    | '/caretaker/new'
    | '/caretaker/sync'
    | '/caretaker/tasks'
    | '/cleaner/sync'
    | '/cleaner/tasks'
    | '/report/new'
    | '/admin'
    | '/caretaker'
    | '/cleaner'
    | '/report'
    | '/staff'
    | '/admin/stock/$itemId'
    | '/admin/stock/scan'
    | '/admin/tasks/$taskId'
    | '/caretaker/tasks/$taskId'
    | '/cleaner/tasks/$taskId'
    | '/staff/$userId/new'
    | '/staff/$userId/sync'
    | '/staff/$userId/tasks'
    | '/staff/$userId'
    | '/staff/$userId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/caretaker'
    | '/cleaner'
    | '/report'
    | '/admin/blocks'
    | '/admin/login'
    | '/admin/new'
    | '/admin/stock'
    | '/admin/sync'
    | '/admin/tasks'
    | '/admin/users'
    | '/caretaker/checklist'
    | '/caretaker/new'
    | '/caretaker/sync'
    | '/caretaker/tasks'
    | '/cleaner/sync'
    | '/cleaner/tasks'
    | '/report/new'
    | '/staff/$userId'
    | '/admin/'
    | '/caretaker/'
    | '/cleaner/'
    | '/report/'
    | '/staff/'
    | '/admin/stock/$itemId'
    | '/admin/stock/scan'
    | '/admin/tasks/$taskId'
    | '/caretaker/tasks/$taskId'
    | '/cleaner/tasks/$taskId'
    | '/staff/$userId/new'
    | '/staff/$userId/sync'
    | '/staff/$userId/tasks'
    | '/staff/$userId/'
    | '/staff/$userId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaretakerRoute: typeof CaretakerRouteWithChildren
  CleanerRoute: typeof CleanerRouteWithChildren
  ReportRoute: typeof ReportRouteWithChildren
  StaffUserIdRoute: typeof StaffUserIdRouteWithChildren
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner': {
      id: '/cleaner'
      path: '/cleaner'
      fullPath: '/cleaner'
      preLoaderRoute: typeof CleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker': {
      id: '/caretaker'
      path: '/caretaker'
      fullPath: '/caretaker'
      preLoaderRoute: typeof CaretakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof ReportRoute
    }
    '/cleaner/': {
      id: '/cleaner/'
      path: '/'
      fullPath: '/cleaner/'
      preLoaderRoute: typeof CleanerIndexRouteImport
      parentRoute: typeof CleanerRoute
    }
    '/caretaker/': {
      id: '/caretaker/'
      path: '/'
      fullPath: '/caretaker/'
      preLoaderRoute: typeof CaretakerIndexRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/$userId': {
      id: '/staff/$userId'
      path: '/staff/$userId'
      fullPath: '/staff/$userId'
      preLoaderRoute: typeof StaffUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/new': {
      id: '/report/new'
      path: '/new'
      fullPath: '/report/new'
      preLoaderRoute: typeof ReportNewRouteImport
      parentRoute: typeof ReportRoute
    }
    '/cleaner/tasks': {
      id: '/cleaner/tasks'
      path: '/tasks'
      fullPath: '/cleaner/tasks'
      preLoaderRoute: typeof CleanerTasksRouteImport
      parentRoute: typeof CleanerRoute
    }
    '/cleaner/sync': {
      id: '/cleaner/sync'
      path: '/sync'
      fullPath: '/cleaner/sync'
      preLoaderRoute: typeof CleanerSyncRouteImport
      parentRoute: typeof CleanerRoute
    }
    '/caretaker/tasks': {
      id: '/caretaker/tasks'
      path: '/tasks'
      fullPath: '/caretaker/tasks'
      preLoaderRoute: typeof CaretakerTasksRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/caretaker/sync': {
      id: '/caretaker/sync'
      path: '/sync'
      fullPath: '/caretaker/sync'
      preLoaderRoute: typeof CaretakerSyncRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/caretaker/new': {
      id: '/caretaker/new'
      path: '/new'
      fullPath: '/caretaker/new'
      preLoaderRoute: typeof CaretakerNewRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/caretaker/checklist': {
      id: '/caretaker/checklist'
      path: '/checklist'
      fullPath: '/caretaker/checklist'
      preLoaderRoute: typeof CaretakerChecklistRouteImport
      parentRoute: typeof CaretakerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blocks': {
      id: '/admin/blocks'
      path: '/blocks'
      fullPath: '/admin/blocks'
      preLoaderRoute: typeof AdminBlocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/$userId/': {
      id: '/staff/$userId/'
      path: '/'
      fullPath: '/staff/$userId/'
      preLoaderRoute: typeof StaffUserIdIndexRouteImport
      parentRoute: typeof StaffUserIdRoute
    }
    '/staff/$userId/tasks': {
      id: '/staff/$userId/tasks'
      path: '/tasks'
      fullPath: '/staff/$userId/tasks'
      preLoaderRoute: typeof StaffUserIdTasksRouteImport
      parentRoute: typeof StaffUserIdRoute
    }
    '/staff/$userId/sync': {
      id: '/staff/$userId/sync'
      path: '/sync'
      fullPath: '/staff/$userId/sync'
      preLoaderRoute: typeof StaffUserIdSyncRouteImport
      parentRoute: typeof StaffUserIdRoute
    }
    '/staff/$userId/new': {
      id: '/staff/$userId/new'
      path: '/new'
      fullPath: '/staff/$userId/new'
      preLoaderRoute: typeof StaffUserIdNewRouteImport
      parentRoute: typeof StaffUserIdRoute
    }
    '/cleaner/tasks/$taskId': {
      id: '/cleaner/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/cleaner/tasks/$taskId'
      preLoaderRoute: typeof CleanerTasksTaskIdRouteImport
      parentRoute: typeof CleanerTasksRoute
    }
    '/caretaker/tasks/$taskId': {
      id: '/caretaker/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/caretaker/tasks/$taskId'
      preLoaderRoute: typeof CaretakerTasksTaskIdRouteImport
      parentRoute: typeof CaretakerTasksRoute
    }
    '/admin/tasks/$taskId': {
      id: '/admin/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/admin/tasks/$taskId'
      preLoaderRoute: typeof AdminTasksTaskIdRouteImport
      parentRoute: typeof AdminTasksRoute
    }
    '/admin/stock/scan': {
      id: '/admin/stock/scan'
      path: '/scan'
      fullPath: '/admin/stock/scan'
      preLoaderRoute: typeof AdminStockScanRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/$itemId': {
      id: '/admin/stock/$itemId'
      path: '/$itemId'
      fullPath: '/admin/stock/$itemId'
      preLoaderRoute: typeof AdminStockItemIdRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/staff/$userId/tasks/$taskId': {
      id: '/staff/$userId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/staff/$userId/tasks/$taskId'
      preLoaderRoute: typeof StaffUserIdTasksTaskIdRouteImport
      parentRoute: typeof StaffUserIdTasksRoute
    }
  }
}

interface AdminStockRouteChildren {
  AdminStockItemIdRoute: typeof AdminStockItemIdRoute
  AdminStockScanRoute: typeof AdminStockScanRoute
}

const AdminStockRouteChildren: AdminStockRouteChildren = {
  AdminStockItemIdRoute: AdminStockItemIdRoute,
  AdminStockScanRoute: AdminStockScanRoute,
}

const AdminStockRouteWithChildren = AdminStockRoute._addFileChildren(
  AdminStockRouteChildren,
)

interface AdminTasksRouteChildren {
  AdminTasksTaskIdRoute: typeof AdminTasksTaskIdRoute
}

const AdminTasksRouteChildren: AdminTasksRouteChildren = {
  AdminTasksTaskIdRoute: AdminTasksTaskIdRoute,
}

const AdminTasksRouteWithChildren = AdminTasksRoute._addFileChildren(
  AdminTasksRouteChildren,
)

interface AdminRouteChildren {
  AdminBlocksRoute: typeof AdminBlocksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminStockRoute: typeof AdminStockRouteWithChildren
  AdminSyncRoute: typeof AdminSyncRoute
  AdminTasksRoute: typeof AdminTasksRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlocksRoute: AdminBlocksRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminStockRoute: AdminStockRouteWithChildren,
  AdminSyncRoute: AdminSyncRoute,
  AdminTasksRoute: AdminTasksRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CaretakerTasksRouteChildren {
  CaretakerTasksTaskIdRoute: typeof CaretakerTasksTaskIdRoute
}

const CaretakerTasksRouteChildren: CaretakerTasksRouteChildren = {
  CaretakerTasksTaskIdRoute: CaretakerTasksTaskIdRoute,
}

const CaretakerTasksRouteWithChildren = CaretakerTasksRoute._addFileChildren(
  CaretakerTasksRouteChildren,
)

interface CaretakerRouteChildren {
  CaretakerChecklistRoute: typeof CaretakerChecklistRoute
  CaretakerNewRoute: typeof CaretakerNewRoute
  CaretakerSyncRoute: typeof CaretakerSyncRoute
  CaretakerTasksRoute: typeof CaretakerTasksRouteWithChildren
  CaretakerIndexRoute: typeof CaretakerIndexRoute
}

const CaretakerRouteChildren: CaretakerRouteChildren = {
  CaretakerChecklistRoute: CaretakerChecklistRoute,
  CaretakerNewRoute: CaretakerNewRoute,
  CaretakerSyncRoute: CaretakerSyncRoute,
  CaretakerTasksRoute: CaretakerTasksRouteWithChildren,
  CaretakerIndexRoute: CaretakerIndexRoute,
}

const CaretakerRouteWithChildren = CaretakerRoute._addFileChildren(
  CaretakerRouteChildren,
)

interface CleanerTasksRouteChildren {
  CleanerTasksTaskIdRoute: typeof CleanerTasksTaskIdRoute
}

const CleanerTasksRouteChildren: CleanerTasksRouteChildren = {
  CleanerTasksTaskIdRoute: CleanerTasksTaskIdRoute,
}

const CleanerTasksRouteWithChildren = CleanerTasksRoute._addFileChildren(
  CleanerTasksRouteChildren,
)

interface CleanerRouteChildren {
  CleanerSyncRoute: typeof CleanerSyncRoute
  CleanerTasksRoute: typeof CleanerTasksRouteWithChildren
  CleanerIndexRoute: typeof CleanerIndexRoute
}

const CleanerRouteChildren: CleanerRouteChildren = {
  CleanerSyncRoute: CleanerSyncRoute,
  CleanerTasksRoute: CleanerTasksRouteWithChildren,
  CleanerIndexRoute: CleanerIndexRoute,
}

const CleanerRouteWithChildren =
  CleanerRoute._addFileChildren(CleanerRouteChildren)

interface ReportRouteChildren {
  ReportNewRoute: typeof ReportNewRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportNewRoute: ReportNewRoute,
  ReportIndexRoute: ReportIndexRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

interface StaffUserIdTasksRouteChildren {
  StaffUserIdTasksTaskIdRoute: typeof StaffUserIdTasksTaskIdRoute
}

const StaffUserIdTasksRouteChildren: StaffUserIdTasksRouteChildren = {
  StaffUserIdTasksTaskIdRoute: StaffUserIdTasksTaskIdRoute,
}

const StaffUserIdTasksRouteWithChildren =
  StaffUserIdTasksRoute._addFileChildren(StaffUserIdTasksRouteChildren)

interface StaffUserIdRouteChildren {
  StaffUserIdNewRoute: typeof StaffUserIdNewRoute
  StaffUserIdSyncRoute: typeof StaffUserIdSyncRoute
  StaffUserIdTasksRoute: typeof StaffUserIdTasksRouteWithChildren
  StaffUserIdIndexRoute: typeof StaffUserIdIndexRoute
}

const StaffUserIdRouteChildren: StaffUserIdRouteChildren = {
  StaffUserIdNewRoute: StaffUserIdNewRoute,
  StaffUserIdSyncRoute: StaffUserIdSyncRoute,
  StaffUserIdTasksRoute: StaffUserIdTasksRouteWithChildren,
  StaffUserIdIndexRoute: StaffUserIdIndexRoute,
}

const StaffUserIdRouteWithChildren = StaffUserIdRoute._addFileChildren(
  StaffUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CaretakerRoute: CaretakerRouteWithChildren,
  CleanerRoute: CleanerRouteWithChildren,
  ReportRoute: ReportRouteWithChildren,
  StaffUserIdRoute: StaffUserIdRouteWithChildren,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
